type FlashType = 'success' | 'info' | 'error'
type Technologies =
  'codeigniter'
  | 'css'
  | 'default_file'
  | 'docker'
  | 'gitlab'
  | 'graphql'
  | 'html'
  | 'java'
  | 'javascript'
  | 'jest'
  | 'kotlin'
  | 'mariadb'
  | 'mongo'
  | 'next'
  | 'php'
  | 'postcss'
  | 'postgresql'
  | 'prisma'
  | 'reactjs'
  | 'symfony'
  | 'typescript'
  | 'vite'
  | 'vue'
  | 'webpack'
  | 'apache'
  | 'rust'
  | 'javafx'